### ISSUE TITLE
Image orientation problem

### ISSUE THREAD

**Issue by G93-7** [portari/MediaPipeUnityPlugin_PoseSample_CPU#1]
I wanted to test the pose sample in the Unity editor. So, I have created a new Unity project and copied the scene, script and config (pose_tracking_vimal.txt) files in the project. I have also copied the entire `MediaPipeUnity` folder from [MediaPipeUnityPlugin](https://github.com/homuler/MediaPipeUnityPlugin) because `PoseVimal.cs` required `AssetLoader` class. The project works but the image and annotations are rotated as shown in the image below. Is there any idea what can be the reason for it?

![pose](https://user-images.githubusercontent.com/80401198/194769883-a4b1da8e-5d0c-4061-a912-42a5de8cbac3.png)

**Comment by portari** [comment]
H @G93-7 i. Just rotate the screen in Canvas. Set Z rotation to 0.
![image](https://user-images.githubusercontent.com/32485137/196016582-e8dd9509-73b3-4749-96de-69cc4f9b65dd.png)
