### ISSUE TITLE
Annotation problem with poseSample_CPU

### ISSUE THREAD

**Issue by limjdong** [portari/MediaPipeUnityPlugin_PoseSample_CPU#2]
Hi, The discussion with you and others on [MediaPipeUnityPlugin](https://github.com/homuler/MediaPipeUnityPlugin) is helpful to me. I really appreciate that.

I have similar task with you, which is to attach MediaPipeUnityPlugin pose tracking to my project.

The discussion what I mentioned above and your git repo is helpful to me. but unfortunatly, It isn't work well

Your code is worked well to me, but annotation for pose landmark does NOT rendered on screen.

I guess some setting at scene on unity is wrong but I have no idea.
Because I'm really newby for UNITY. (It's my first unity project🥲)

Could you give me help for it?

here is what I did
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/113662106/196624236-f22b1296-cd61-4464-9d37-90d5eb9b5158.png">
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/113662106/196624568-b9b14540-b2b0-4b48-9f1b-5ce5517af754.png">
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/113662106/196624622-b7d6e484-439a-4ccb-8c29-fff519f3f7d6.png">

What can I do to render landmark on screen?

Thank you.

Best regards.

**Comment by limjdong** [comment]
Additionally, I learned to "copy scene" in your repo right now. but still don't know what is different between yours and what I set🥲

**Comment by portari** [comment]
@limjdong Hello. Hope you're well.

I don't know how you tried to do it, but I suggest downloading the entire repository as a ZIP, extracting it into a folder and adding the whole project to the Unity Hub. If you only copied the scene, you may be missing several elements from the plugin, scripts, etc.
If not, please provide more details so I can try to help you.
Sergio Portari.

![image](https://user-images.githubusercontent.com/32485137/196791810-e8df2448-4268-412f-a383-1de3222bebc8.png)

then select the root of the folder
![image](https://user-images.githubusercontent.com/32485137/196791971-b2968026-9c1b-49b0-a337-972367b1c548.png)

**Comment by limjdong** [comment]
@portari Hi! Thanks for advice and it works well😀

I have had two task with MediaPipeUnityPlugin, pose tracking and multi hand tracking. So I tried to build pose tracking by myself to apply it to hand tracking. 
I need to study more how build pose tracking plugin based yours!

I really appreciate your help! and I will come back to share hand tracking application:)

Thank you!

Best Regards, Lim Jungdong

**Comment by portari** [comment]
@limjdong  Cool knows it worked.
When you have the project ready, be sure to show the result to see how it turned out. Good luck.
